### PR TITLE
fix(neuron.connection.http): fix error case so return value matches t…

### LINKED ISSUE #59: Bug in returning a JSONParseError
`Neuron.Connection.Http` can return a `JSONParseError` (https://github.com/uesteibar/neuron/blob/master/lib/neuron/connection/http.ex#L73):

```elixir
  defp handle_unparsable(response, error) do
    {
      :error,
      %JSONParseError{
        response: build_response(response),
        error: error
      }
    }
  end
```

According to the typespec for `JSONParseError`, `response` is supposed to be a `Neuron.Response.t()`, but `build_response/1` returns a tuple (https://github.com/uesteibar/neuron/blob/master/lib/neuron/connection/http.ex#L62):

```elixir
  defp build_response(response) do
    {
      :error,
      %Response{
        status_code: response.status_code,
        body: response.body,
        headers: response.headers
      }
    }
  end
```

### PR DESCRIPTION
**Pull request by krisalyssa**
…ypespec

The definition of the `JSONParseError` struct says that the `response` element is a
`Neuron.Response.t()`, but the code was actually returning a tuple (`{:error,
Neuron.Response.t()}`). With this change the type of `response` matches the typespec.

BREAKING CHANGE: If your code expects the `response` field of `JSONParseError` to be a tuple, it
will break.

fix #59

### CODE REVIEW

**Comment by uesteibar** [comment]
Hi there! thanks for taking care of this ❤️ however there is some tests failing that we should fix first, you can see it on https://travis-ci.org/github/uesteibar/neuron/builds/685800174.

Not sure why it's not showing in here, I'll investigate

**Comment by krisalyssa** [comment]
I'm finally circling back to check on these failing tests. The first thing I notice is that TravisCI is building using older versions of Elixir and Erlang than I did when developing, and it looks like something's trying to use a function that's not available in the older Erlang. I'm installing OTP 19.0 and Elixir 1.6.6 to see if and how I need to adjust my PR.

**Comment by krisalyssa** [comment]
@uesteibar I was unable to get OTP 19.0 to install successfully on macOS 10.15, so I can't recreate the error that TravisCI is reporting. So I'm making educated guesses based on what I can see in TravisCI, and editing the code in the PR to what I hope will be more OTP 19-friendly. There may be several code pushes until I get it right, since the only way I can tell is to have TravisCI run the tests here.

**Comment by krisalyssa** [comment]
That push appears to have fixed the tests.

File: lib/neuron/connection/http.ex [hunk 1]
```diff
@@ -40,33 +40,33 @@ defmodule Neuron.Connection.Http do
...
+      {:ok, body} -> build_response_tuple(%{response | body: body})
       {:error, error} -> handle_unparsable(response, error)
       {:error, error, _} -> handle_unparsable(response, error)
     end
   end
 
   defp handle({:error, _} = response, _, _), do: response
 
-  defp build_response(%{status_code: 200} = response) do
+  defp build_response(response) do
```
Comment (uesteibar) [inline lib/neuron/connection/http.ex]: Can we change the order and put `build_response` _after_ `build_response_tuple`? The former is used by the later so that is (imo) easier to read.

**Review by uesteibar — COMMENTED** [review]
Thanks for taking care of this! just a tiny thing, after that I'll merge and release 👏 ❤️

File: lib/neuron/connection/http.ex (hunk 1 above)
Comment (krisalyssa) [reply lib/neuron/connection/http.ex]: Done.

**Comment by uesteibar** [comment]
Published as `v5.0.0` 🚀 thank you!

**Comment by krisalyssa** [comment]
You're very welcome! `neuron` has been useful to us, so I'm happy to give something back.
